export const ADDITIONAL_COLS = Array.from({ length: 20 }, (_, i) => `additional_${i + 1}`);

export const ITEM_MASTER_BASE_COLS = [
  'item_uid', 'name', 'manufacturer_uid', 'brand_uid',
  'is_fractional', 'is_deleted', 'main_unit_uid', 'erp_category_uid',
];

export const ENTITY_COLUMNS: Record<string, string[]> = {
  // Main entities
  ITEM_MASTER:    [...ITEM_MASTER_BASE_COLS, ...ADDITIONAL_COLS],
  FACTS:          ['item_uid', 'store_uid', 'date', 'stock', 'sold_qty', 'revenue', 'cogs'],
  STORE_ITEMS:    ['item_uid', 'store_uid', 'is_active_planogram', 'purchase_price', 'retail_price', 'external_supplier_uid'],
  STORE:          ['store_uid', 'name', 'region', 'group_name', 'floor_space', 'in_shelf', 'licence_start_date', 'is_deleted'],
  USER_STORES:    ['user_uid', 'store_uid', 'is_deleted'],
  USERS:          ['user_uid', 'username', 'email', 'role', 'is_deleted'],
  // Supplementary (generated by converter)
  BARCODES:       ['item_uid', 'barcode', 'is_main'],
  BRANDS:         ['brand_uid', 'name', 'is_deleted'],
  DIMENSIONS:     ['item_uid', 'unit_name', 'width', 'height', 'depth', 'netweight', 'volume', 'dimension_uid', 'coef', 'is_deleted'],
  ERP_CATEGORIES: ['erp_category_uid', 'name', 'parent_category_uid'],
  MANUFACTURERS:  ['manufacturer_uid', 'name', 'is_deleted'],
  SUPPLIERS:      ['supplier_uid', 'name', 'is_deleted'],
  // Converter-only
  STOCK:          ['store_uid', 'item_uid', 'stock'],
  PRICE:          ['item_uid', 'price_list', 'price'],
};

export type EntityType = keyof typeof ENTITY_COLUMNS;

export const ENTITY_LABELS: Record<string, string> = {
  ITEM_MASTER:    'Masteritems',
  FACTS:          'Facts',
  STORE_ITEMS:    'Items',
  STORE:          'Stores',
  USER_STORES:    'User Stores',
  USERS:          'Users',
  BARCODES:       'Barcodes',
  BRANDS:         'Brands',
  DIMENSIONS:     'Dimensions',
  ERP_CATEGORIES: 'ERP Categories',
  MANUFACTURERS:  'Manufacturers',
  SUPPLIERS:      'Suppliers',
  STOCK:          'Stock',
  PRICE:          'Prices',
};

// Types available in Manual Editor selector
export const EDITOR_ENTITY_TYPES = [
  'ITEM_MASTER', 'FACTS', 'STORE_ITEMS', 'STORE',
  'USER_STORES', 'USERS',
  'BARCODES', 'BRANDS', 'DIMENSIONS', 'ERP_CATEGORIES', 'MANUFACTURERS', 'SUPPLIERS',
] as const satisfies readonly (keyof typeof ENTITY_COLUMNS)[];

// Maps CSV filename prefix → EntityType (for "Send to Editor" from Converter)
export const CSV_PREFIX_TO_ENTITY: Record<string, EntityType> = {
  masteritems:    'ITEM_MASTER',
  facts:          'FACTS',
  items:          'STORE_ITEMS',
  stores:         'STORE',
  barcodes:       'BARCODES',
  brands:         'BRANDS',
  dimensions:     'DIMENSIONS',
  erpcategories:  'ERP_CATEGORIES',
  manufacturers:  'MANUFACTURERS',
  suppliers:      'SUPPLIERS',
  stock:          'STOCK',
  price:          'PRICE',
};
